### ISSUE TITLE
OpenStereo can't launch

### ISSUE THREAD

**Issue by raulindo** [spamlab-iee/os#19]
Hi Arthur! I've successfully installed OpenStereo, however I couldn't launch it! This is what I got:

(OS) Raul-Santana:~ raulsantana$ python -m openstereo
Traceback (most recent call last):
  File "/Users/raulsantana/anaconda3/envs/OS/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/raulsantana/anaconda3/envs/OS/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/raulsantana/anaconda3/envs/OS/lib/python2.7/site-packages/openstereo/__main__.py", line 2, in <module>
    from openstereo.os_base import os_main
  File "/Users/raulsantana/anaconda3/envs/OS/lib/python2.7/site-packages/openstereo/os_base.py", line 40, in <module>
    from openstereo.io import get_data, ImportDialog, Importer
  File "/Users/raulsantana/anaconda3/envs/OS/lib/python2.7/site-packages/openstereo/io.py", line 95
    **self.dialect,  # should it skip comments?
.                      (on terminal, "invalid syntax" is shown right below the comma on self.dialect,) 
SyntaxError: invalid syntax

**Comment by endarthur** [comment]
Hi Raulindo!

OpenStereo currently runs on python3, mostly thanks to issues with unicode. Could you try installing python 3 and running, either through homebrew or some other method?

**Comment by raulindo** [comment]
Olá Arthur, 

Estou no email que o Prof Ginaldo enviou para a gente. Eu tenho o python3 instalado! Devo tentar reinstalar o OpenStereo?

Eu realmente não sei o que fazer haha

Grato!

Raul Santana
raul.santananeto@gmail.com
